package wasm-version-tests:component;

interface clients { 
  hello-world: func() -> string;


}

interface events { 
  record foo {
    bar: string,
  }

  parse: func(input: string) -> result<foo, string>;
}

world wasm-version-tests { 
  export clients;
  export events;
}
