[package]
name = "wasm_version_tests"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen =  "0.16.0"
serde = {version = "1.0.193", features = ["derive"]}
serde_json = "1.0.108"
