package wasi-http-tests:component;
//use wasi:http/outgoing-handler@0.2.0-rc-2023-12-05;

interface client { 
  //If you are creating new clients implement them inside of this interface
  resource wasi-http-tests-client {
    constructor();
    http-call: func(sleep: u16) -> result<string, string>;
  }
}

world wasi-http-tests { 
  import wasi:http/outgoing-handler@0.2.0-rc-2023-12-05;
  export client;
}
